### ISSUE TITLE
[BUG] Debian Repository Error

### ISSUE THREAD

**Issue by raoulschaffner** [Uninett/nav-debian#13]
**Describe the bug**
Installation instructions on https://nav.uninett.no/install-instructions/#debian lead to error

**To Reproduce**
Try to execute the 5 commands on above page, command 4 leads to error:
N: Skipping acquire of configured file 'nav/binary-amd64/Packages' as repository 'https://nav.uninett.no/debian buster InRelease' doesn't support architecture 'amd64'

**Expected behavior**
Repository should provide packages for architecture 'amd64'

**Environment (please complete the following information):**
Debian 10 Buster 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux

**Comment by lunkwill42** [comment]
Indeed, we have recently changed the toolset used to publish the APT repository.

The package was never built for the amd64 architecture specifically, since NAV consists of all platform-independent code. Why the old index published it under `binary-amd64` is beyond me.

(There may, however, be an exception in this, since most of the Python dependencies of NAV are bundled in the Debian package itself, and some of those may actually have been compiled to interface against various C libraries in versions made available by Debian on amd64 - I'll have to check that out...)

The new toolset publishes the current package version more correctly under `binary-all`.

As far as I can tell, this error message is just a warning, and does not prevent one from getting packages from the repository. You should be able to get rid of the warning by replacing `deb https://nav.uninett.no/debian buster nav` with `deb [arch=all] https://nav.uninett.no/debian buster nav`. I'll update the instructions on the website.
