### ISSUE TITLE
Please remove systemd dependency

### ISSUE THREAD

**Issue by beren12** [Uninett/nav-debian#14]
**Is your feature request related to a problem? Please describe.**
I can't install this without installing systemd

**Describe the solution you'd like**
Remote the depends on it, possibly add an init file.

**Describe alternatives you've considered**
I doubt the container requires systemd

**Additional context**

**Comment by lunkwill42** [comment]
I'll have to look at this in our next dev sprint. IIRC, the dependency to systemd is because the package actually uses systemctl commands directly to start/stop NAV services during package installs/upgrades.

If you know of some portable way of achieving service start/stop across different init systems on Debian, I'm all ears (we just went with what Debian picked as their default).

**Comment by lunkwill42** [comment]
As suspected, the package is built specifically to integrate with systemd. So the question remains, @beren12 , whether you know of a more portable way to build the package.

**Comment by lunkwill42** [comment]
Closing, in lack of feedback.
