### ISSUE TITLE
Latest stable Debian 9.1

### ISSUE THREAD

**Issue by TonyMedKniven** [UNINETT/nav-debian#2]
Hi

I'm reluctant to install older than latest stable and the package has dependencies that are held i 9.1. Will this be looked into?

Also the appliance .ovf has hw specs that aren't accepted by vsphere.

ie. evaluation of this is going slow.

**Comment by lunkwill42** [comment]
The initial package for Debian 9 was built less than two weeks ago. We haven't noticed any problems so far, so which packages are you referring to, specifically?

Also, the appliance has nothing to do with the Debian packaging project (use [OVFtool](https://www.vmware.com/support/developer/ovf/), as the install instructions mention; vSphere&Co are dumb)

**Comment by TonyMedKniven** [comment]
I'm sorry I was there before that ie. <2w, also, I'm the same guy
tony.gottfridsson@hig.se. complaining via other lanes. :-D

I have major daily stuff to fix but the comming week I'l try to get some
time to start the appliance version and let the network guy loose on it
after I've examined the config/data storage alternatives that allow for
future production implementation.

I'm sorry if I was "hard" saying abandonware, I'm simply being direct and
clear in what I see. I did notice who use it, but when I checked it was
slow on the bug site (you informed me about why) and deb8 was the only
alternative and so on. I'm "on the boat now. You answered bot @work and
here so I'll set this up and force the network guy to go to work on it when
I made it run. To be completely honest my feeling is that mr sunet "herr
nilsson" want's us to evaluate this.. before he promotes/enforces this on
his end. I mean... he sent us to you and there is no sunet testing from
what I can see.

Are u involved with eduroam also? I haven't had the time to join the
mailing lists for it yet. I do need to check on that stuff too... omg I
love my job it's a never ending stream of hurdles to pass. :-D

I hope u have a nice weekend!

/Tony Gottfridsson





      /Best Regards Tony Gottfridsson

On Tue, Sep 19, 2017 at 1:26 PM, Morten Brekkevold <notifications@github.com

**Comment by lunkwill42** [comment]
> so I'll set this up and force the network guy to go to work on it when
> I made it run. To be completely honest my feeling is that mr sunet
> "herr nilsson" want's us to evaluate this.. before he
> promotes/enforces this on his end. I mean... he sent us to you and
> there is no sunet testing from what I can see.

As far as I understand, SUNET may be interested in using NAV for their
"Network as a Service", but I have no details on that yet.

I know Linköping University and Chalmers University are using NAV in
Sweden. In Norway, more than 95% of universities and university colleges
are using it, so there is a largish Nordic higher education community
here.

I recommend subscribing to the nav-users mailing list for future
questions: https://sympa.uninett.no/lists/uninett.no/subscribe/nav-users

> Are u involved with eduroam also?

Not personally, no, but UNINETT is, of course :-)

Since there is no actual bug to discuss here, I'm going to close the
tracker issue.

-- 
Morten Brekkevold
UNINETT
